version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:YOUR_APP_KEY
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: sprintcode
      DB_USERNAME: root
      DB_PASSWORD: 1KRnqNSb7bo2T8GiqznCeSjNSXIrN9Q7

  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sprintcode
      MYSQL_USER: root
      MYSQL_PASSWORD: 1KRnqNSb7bo2T8GiqznCeSjNSXIrN9Q7
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
