version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: sprintcode
      DB_USERNAME: root
      DB_PASSWORD: 1KRnqNSb7bo2T8GiqznCeSjNSXIrN9Q7
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: laravel-db
    restart: always
    environment:
      POSTGRES_DB: sprintcode
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1KRnqNSb7bo2T8GiqznCeSjNSXIrN9Q7
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
